# Generated by Django 5.0.6 on 2024-05-26 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_contactphone_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactphone',
            old_name='phone',
            new_name='number',
        ),
    ]
